[package]
name = "neural-networks"
version = "0.1.0"
edition = "2024"

[profile.release]
lto = "fat"
codegen-units = 1

[[bench]]
name = "lstm_training"
harness = false

[dev-dependencies]
criterion = "0.4"

[dependencies]
iron_oxide = { path = "../iron_oxide" }
rand = "0.9.2"